AWSTemplateFormatVersion: "2010-09-09"
Description: This is the main infrastructure file 

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/infrastructurefiles/vpc.yml
  
  SGStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/infrastructurefiles/security_group.yml
      Parameters:
        VPCID: !GetAtt VPCStack.Outputs.VPCID 
  
  EC2Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/infrastructurefiles/ec.yml
      Parameters:
        SecurityGroupID: !GetAtt SGStack.Outputs.SecurityGroupID
        SubnetID: !GetAtt VPCStack.Outputs.SubnetID

Outputs:
  InstanceId:
    Description: EC2 instance ID
    Value: !GetAtt EC2Stack.Outputs.InstanceId

  PublicIpAddress:
    Description: EC2 public Ip address
    Value: !GetAtt EC2Stack.Outputs.PublicIP