AWSTemplateFormatVersion: "2010-09-09"  
Description: Security Group Yml file

Parameters:
  VPCID:
    Type: String

Resources:
  InfraSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and HTTP
      VpcId: !Ref VPCID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

Outputs:
  SecurityGroupID:
    Description: SG ID
    Value: !Ref InfraSecurityGroup